services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: challenge_formation
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_DATABASE: challenge_formation
      PMA_USER: user
      PMA_PASSWORD: password
      PMA_PORT: 3306
    ports:
      - "8080:80"

  php:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./infra/volumes/dev/composer:/root/.composer
      - ./infra/php/dev/project.ini:/usr/local/etc/php/conf.d/project.ini:ro
      - ./app:/var/www/app
    environment:
      APP_ENV: dev
    depends_on:
      - db
    tty: true

  nginx:
    image: nginx:latest
    volumes:
      - ./infra/volumes/dev/logs/nginx:/var/log/nginx
      - ./infra/nginx/dev/virtualhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/app
    ports:
      - "80:80"
    depends_on:
      - php
    tty: true

  mailcatcher:
    restart: on-failure
    image: schickling/mailcatcher
    ports: [ 1025:1025, 1080:1080 ]

volumes:
  db_data: