controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
invite_student:
    path: /inviter-eleve
    controller: App\Controller\InvitationController::invite
    methods: [POST]
